
CC := g++

OPTS := -Wall -Wextra

EIGEN_ROOT := /home/2017/pzwane/Desktop/programs/eigen-eigen-5a0156e40feb

ex1:
	$(CC) $(OPTS) -I $(EIGEN_ROOT) ex1.cpp

ex2:
	$(CC) $(OPTS) -I $(EIGEN_ROOT) ex2.cpp
