# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

#before_install:
#  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
install:
  ############################################################################
  # Install a recent CMake (Copied from boostorg/hana)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake_download && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake_download
      export PATH=${DEPS_DIR}/cmake_download/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
#    - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
    packages:
    - g++-7
#    - clang-6.0
#    - lldb-6.0
#    - lld-6.0
    - valgrind
os:
  - linux
language: cpp
compiler:
  - g++
#  - clang
script: bash travis.sh
env:
  matrix:
    - PEGASUS_CMAKE_RUN=gnu-7_debug
#    - PEGASUS_CMAKE_RUN=clang-6_debug
#    - GTEST_TARGET=googletest SHARED_LIB=OFF STATIC_LIB=ON CMAKE_PKG=OFF BUILD_TYPE=debug   VERBOSE_MAKE=true VERBOSE
#    - GTEST_TARGET=googlemock SHARED_LIB=OFF STATIC_LIB=ON CMAKE_PKG=OFF BUILD_TYPE=debug   VERBOSE_MAKE=true VERBOSE
#    - GTEST_TARGET=googlemock SHARED_LIB=OFF STATIC_LIB=ON CMAKE_PKG=OFF BUILD_TYPE=debug CXX_FLAGS=-std=c++11  VERBOSE_MAKE=true VERBOSE
#    - GTEST_TARGET=googletest SHARED_LIB=ON  STATIC_LIB=ON CMAKE_PKG=ON  BUILD_TYPE=release VERBOSE_MAKE=false
#    - GTEST_TARGET=googlemock SHARED_LIB=ON  STATIC_LIB=ON CMAKE_PKG=ON  BUILD_TYPE=release VERBOSE_MAKE=false
notifications:
  email: false
sudo: false
