# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

#before_install:
#  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
install: 
  # (boostorg/hana was used as an example for `install:`)
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

  # Install Doxygen (Graphviz does not come with the `dot` executable...)
# Fix the if condition.
#    if [[ "${DOCUMENTATION}" == "true" ]]; then
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.linux.bin.tar.gz"
      mkdir doxygen && travis_retry wget --quiet -O - ${DOXYGEN_URL} | tar --strip-components=1 -xz -C doxygen
      export PATH=${DEPS_DIR}/doxygen/bin:${PATH}
      doxygen --version
    fi

  # Back to ${TRAVIS_BUILD_DIR}
  - cd ..
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
#    - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
    packages:
    - g++-7
#    - clang-6.0
#    - lldb-6.0
#    - lld-6.0
    - lcov
    - valgrind
os:
  - linux
language: cpp
compiler:
  - g++
#  - clang
script: ./travis.sh
env:
  matrix:
    - PEGASUS_CMAKE_RUN=gnu-7_debug
#    - PEGASUS_CMAKE_RUN=clang-6_debug

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*'      --output-file coverage.info # filter out system
  - lcov --remove coverage.info '/external/*' --output-file coverage.info # filter out external
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  email: false
sudo: false
